# Generated by Django 5.0.6 on 2024-07-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='licensing_information',
            field=models.TextField(),
        ),
    ]
