# Generated by Django 5.0.6 on 2024-07-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_alter_hospital_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
