# Generated by Django 5.0.6 on 2024-07-04 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_alter_hospital_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='user',
        ),
    ]
