# Generated by Django 5.0.6 on 2024-07-04 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_remove_hospital_user'),
        ('hospital', '0005_hospital_role_remove_doctor_hospital_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
