# Generated by Django 5.0.6 on 2024-07-04 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='medical_history',
        ),
    ]
