# Generated by Django 5.0.6 on 2024-07-04 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_alter_hospital_name'),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialty',
            new_name='specialization',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.AddField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(default='first', max_length=25),
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(default='last', max_length=25),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_number',
            field=models.CharField(default='123456789', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='first', max_length=25),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='last', max_length=25),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='contact_number',
            field=models.CharField(default='123456789', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.hospital'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.hospital'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
