# Generated by Django 5.0.6 on 2024-07-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_alter_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='additional_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
