# Generated by Django 5.0.6 on 2024-07-05 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_alter_appointment_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], max_length=50, unique=True),
        ),
    ]
