# Generated by Django 5.0.6 on 2024-07-05 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_alter_role_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
